### ISSUE TITLE
actionbar GCD cooldown flash issue

### ISSUE THREAD

**Issue by fafaraway** [zorker/rothui#39]
Hey zork
This is my bar3 config, shows only on mouseover, but still can see GCD cooldown flash, is this a bug or I miss something?
rActionbar and rLIb are all latest.

```lua
local bar3 = {
	framePoint      = { "BOTTOM", A.."Bar2", "TOP", 0, 0 },
	frameScale      = 1,
	framePadding    = 0,
	buttonWidth     = 30,
	buttonHeight    = 30,
	buttonMargin    = 4,
	numCols         = 12,
	startPoint      = "BOTTOMLEFT",
	fader = {
		fadeInAlpha = 1,
		fadeInDuration = 0.3,
		fadeInSmooth = "OUT",
		fadeOutAlpha = 0,
		fadeOutDuration = 0.3,
		fadeOutSmooth = "OUT",
		fadeOutDelay = 0,
	},
}
```

![wow-64 2016-12-09 00-01-20](https://cloud.githubusercontent.com/assets/156806/21017095/21292e7a-bda3-11e6-8e3a-6531cc033134.png)

**Comment by zorker** [comment]
What version of rLib are you using? I applied a fix lately that fixed another annoying bug with the WoW animation api where all subregions on an animated region using alpha transition became visible aswell. This is fixed here: https://github.com/zorker/rothui/commit/87647fee06a11e111d360caad4a3128b8a6b569b

Maybe this fixes your flash texture alpha bug aswell.

**Comment by fafaraway** [comment]
Yes, I already updated this commit, rActionbar and rLIb are all latest, but issue still remains :confounded:

**Comment by zorker** [comment]
Damn. :(
Yeah the flash becoming visible even when the frame is hidden is a known issue.
Something is wrong with that animation on the flash texture.

**Comment by fafaraway** [comment]
found a perfect solution, maybe you can use it to fix the problem

```lua
hooksecurefunc(getmetatable(ActionButton1Cooldown).__index, 'SetCooldown', function(self)
	local alpha = self:GetEffectiveAlpha()
	if alpha > 0.001 then
		self:SetSwipeColor(0,0,0,alpha)
		self:Show()
	else
		self:Hide()
	end
end)
```
